services:
  - type: web
    name: pest-ai-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_feuille:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
