services:
  - type: web
    name: pestai-api
    runtime: python
    pythonVersion: 3.11.8  # ou 3.10.12, selon compatibilité de tes libs
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_feuille:app --host=0.0.0.0 --port=$PORT
    plan: free
    region: frankfurt
    branch: main
    repo: https://github.com/Gblack98/nouveau_test_api
