services:
  - type: web
    name: pestai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_feuille:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
